### ISSUE TITLE
DBM-VV

### ISSUE THREAD

**Issue by nanjuekaien1** [siweia/FullPack#5]
补齐VV缺失的DBM语音文件
[DBM-VV.zip](https://github.com/siweia/FullPack/files/13059942/DBM-VV.zip)

**Comment by Lino-saur** [comment]
大佬这个怎么用

**Comment by nanjuekaien1** [comment]
@LoKiLyn  DBM 10.2的语音包建议你去cur上下载桃桃、jingjing、顾衣衿的他们都补齐了
VV的暂时缺少了阿梅达希尔里面团本的4个语音文档。
以上3个人的语音包NGA也能找到。
